// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ddlcmd

import (
	"github.com/fntsky/ddl_guard/internal/base/OTP"
	"github.com/fntsky/ddl_guard/internal/base/auth"
	"github.com/fntsky/ddl_guard/internal/base/data"
	"github.com/fntsky/ddl_guard/internal/base/server"
	"github.com/fntsky/ddl_guard/internal/controller"
	"github.com/fntsky/ddl_guard/internal/repo/ddl"
	"github.com/fntsky/ddl_guard/internal/repo/exam"
	"github.com/fntsky/ddl_guard/internal/repo/session"
	"github.com/fntsky/ddl_guard/internal/repo/user"
	"github.com/fntsky/ddl_guard/internal/router"
	"github.com/fntsky/ddl_guard/internal/service/ai"
	auth2 "github.com/fntsky/ddl_guard/internal/service/auth"
	ddl2 "github.com/fntsky/ddl_guard/internal/service/ddl"
	exam2 "github.com/fntsky/ddl_guard/internal/service/exam"
	user2 "github.com/fntsky/ddl_guard/internal/service/user"
	"github.com/fntsky/ddl_guard/internal/worker"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func initApplication(debug bool) (*app, func(), error) {
	swaggerRouter := router.NewSwaggerRouter()
	tokenService, err := auth.NewTokenService()
	if err != nil {
		return nil, nil, err
	}
	engine, err := data.NewDB(debug)
	if err != nil {
		return nil, nil, err
	}
	redisClient, cleanup, err := data.NewRedisClient()
	if err != nil {
		return nil, nil, err
	}
	dataData, err := data.NewData(engine, redisClient)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	sessionRepo := session.NewSessionRepo(dataData)
	authService := auth2.NewAuthService(tokenService, sessionRepo)
	authController := controller.NewAuthController(authService)
	authApiRouter := router.NewAuthApiRouter(authController)
	ddlRepo := ddl.NewDDLRepo(dataData)
	aiProvider := ai.NewAIProvider()
	ddlService := ddl2.NewDDLService(ddlRepo, aiProvider)
	ddlController := controller.NewDDLController(ddlService)
	ddlApiRouter := router.NewDDLApiRouter(ddlController, tokenService)
	examRepo := exam.NewExamRepo(dataData)
	examService := exam2.NewExamService(examRepo)
	examController := controller.NewExamController(examService)
	examApiRouter := router.NewExamApiRouter(examController, tokenService)
	userRepo := user.NewUserRepo(dataData)
	otpOTP := otp.NewSMTPEmailOTP(redisClient)
	userService := user2.NewUserService(userRepo, otpOTP, authService)
	userController := controller.NewUserController(userService)
	userApiRouter := router.NewUserApiRouter(userController)
	ginEngine := server.NewHttpServer(debug, swaggerRouter, authApiRouter, ddlApiRouter, examApiRouter, userApiRouter)
	publishWorker := worker.NewPublishWorker(ddlRepo, userRepo, redisClient)
	expirationWorker := worker.NewExpirationWorker(ddlRepo)
	ddlcmdApp := newApp(debug, ginEngine, publishWorker, expirationWorker)
	return ddlcmdApp, func() {
		cleanup()
	}, nil
}

// wire.go:

type app struct {
	HttpServer       *gin.Engine
	PublishWorker    *worker.PublishWorker
	ExpirationWorker *worker.ExpirationWorker
}

func newApp(debug bool, httpServer *gin.Engine, pw *worker.PublishWorker, ew *worker.ExpirationWorker) *app {
	return &app{
		HttpServer:       httpServer,
		PublishWorker:    pw,
		ExpirationWorker: ew,
	}
}

func (a *app) StartWorkers() {
	if a.PublishWorker != nil {
		a.PublishWorker.Start()
	}
	if a.ExpirationWorker != nil {
		a.ExpirationWorker.Start()
	}
}
