// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package ddlcmd

import (
	"github.com/fntsky/ddl_guard/internal/base/data"
	"github.com/fntsky/ddl_guard/internal/base/server"
	"github.com/fntsky/ddl_guard/internal/controller"
	"github.com/fntsky/ddl_guard/internal/repo/ddl"
	"github.com/fntsky/ddl_guard/internal/router"
	ddl2 "github.com/fntsky/ddl_guard/internal/service/ddl"
	"github.com/gin-gonic/gin"
)

// Injectors from wire.go:

func initApplication(debug bool) (*app, func(), error) {
	swaggerRouter := router.NewSwaggerRouter()
	engine, err := data.NewDB(debug)
	if err != nil {
		return nil, nil, err
	}
	dataData, err := data.NewData(engine)
	if err != nil {
		return nil, nil, err
	}
	ddlRepo := ddl.NewDDLRepo(dataData)
	ddlService := ddl2.NewDDLService(ddlRepo)
	ddlController := controller.NewDDLController(ddlService)
	ddlApiRouter := router.NewDDLApiRouter(ddlController)
	ginEngine := server.NewHttpServer(debug, swaggerRouter, ddlApiRouter)
	ddlcmdApp := newApp(debug, ginEngine)
	return ddlcmdApp, func() {
	}, nil
}

// wire.go:

type app struct {
	HttpServer *gin.Engine
}

func newApp(debug bool, httpServer *gin.Engine) *app {
	return &app{
		HttpServer: httpServer,
	}
}
