// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/refresh-tokens": {
            "post": {
                "description": "使用refresh token换取新的access token和refresh token",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Auth"
                ],
                "summary": "刷新Token",
                "parameters": [
                    {
                        "description": "Refresh Token Request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.RefreshTokenReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_base_handler.resp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.TokenPairResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ddl/draft": {
            "post": {
                "description": "创建DDL草稿",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DDL"
                ],
                "summary": "创建DDL草稿",
                "parameters": [
                    {
                        "description": "Create Draft Request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.CreateDraftReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_base_handler.resp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.CreateDraftResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ddl/drafts/{uuid}": {
            "patch": {
                "description": "将草稿状态从draft变更为active",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DDL"
                ],
                "summary": "同意DDL草稿",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Draft UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Draft Status Request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.UpdateDraftStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_base_handler.resp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.UpdateDraftStatusResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/users/email/verification-codes": {
            "post": {
                "description": "发送邮箱验证码用于注册",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "发送邮箱验证码",
                "parameters": [
                    {
                        "description": "Send Email Verification Code Request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.SendEmailVerificationCodeReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_base_handler.resp"
                        }
                    }
                }
            }
        },
        "/users/registrations/email": {
            "post": {
                "description": "使用邮箱验证码注册用户",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "User"
                ],
                "summary": "邮箱注册",
                "parameters": [
                    {
                        "description": "Register User By Email Request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.RegisterUserByEmailReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_base_handler.resp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.RegisterUserByEmailResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "github_com_fntsky_ddl_guard_internal_base_handler.resp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.CreateDraftInput": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-03-24T14:30:00+08:00"
                },
                "description": {
                    "type": "string",
                    "example": "from swagger"
                },
                "early_remind": {
                    "type": "integer",
                    "example": 30
                },
                "title": {
                    "type": "string",
                    "example": "test ddl"
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.CreateDraftReq": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string",
                    "default": "default",
                    "example": "default"
                },
                "draft": {
                    "$ref": "#/definitions/github_com_fntsky_ddl_guard_internal_schema.CreateDraftInput"
                },
                "raw_base64": {
                    "type": "string",
                    "example": "iVBORw0KGgoAAAANSUhEUgAA..."
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.CreateDraftResp": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-03-24T14:30:00+08:00"
                },
                "description": {
                    "type": "string",
                    "example": "from swagger"
                },
                "early_remind": {
                    "type": "integer",
                    "example": 30
                },
                "title": {
                    "type": "string",
                    "example": "test ddl"
                },
                "uuid": {
                    "type": "string",
                    "example": "7a178766-4b8e-4e99-ab4c-843f7dbd95fd"
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.RefreshTokenReq": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.RegisterUserByEmailReq": {
            "type": "object",
            "required": [
                "code",
                "email",
                "password",
                "username"
            ],
            "properties": {
                "code": {
                    "type": "string",
                    "example": "123456"
                },
                "email": {
                    "type": "string",
                    "example": "testuser@example.com"
                },
                "password": {
                    "type": "string",
                    "minLength": 6,
                    "example": "password123"
                },
                "username": {
                    "type": "string",
                    "example": "testuser"
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.RegisterUserByEmailResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "uuid": {
                    "type": "string",
                    "example": "7a178766-4b8e-4e99-ab4c-843f7dbd95fd"
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.SendEmailVerificationCodeReq": {
            "type": "object",
            "required": [
                "email"
            ],
            "properties": {
                "email": {
                    "type": "string",
                    "example": "testuser@example.com"
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.TokenPairResp": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                },
                "refresh_token": {
                    "type": "string",
                    "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.UpdateDraftStatusReq": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "github_com_fntsky_ddl_guard_internal_schema.UpdateDraftStatusResp": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "uuid": {
                    "type": "string",
                    "example": "7a178766-4b8e-4e99-ab4c-843f7dbd95fd"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DDL Guard API",
	Description:      "This is a DDL Guard server API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
