// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/ddl/draft": {
            "post": {
                "description": "创建DDL草稿",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DDL"
                ],
                "summary": "创建DDL草稿",
                "parameters": [
                    {
                        "description": "Create Draft Request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.CreateDraftReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.resp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/schema.CreateDraftResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/ddl/drafts/{uuid}": {
            "patch": {
                "description": "将草稿状态从draft变更为active",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "DDL"
                ],
                "summary": "同意DDL草稿",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Draft UUID",
                        "name": "uuid",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Draft Status Request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/schema.UpdateDraftStatusReq"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/handler.resp"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/schema.UpdateDraftStatusResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.resp": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "message": {
                    "type": "string"
                }
            }
        },
        "schema.CreateDraftInput": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-03-24T14:30:00+08:00"
                },
                "description": {
                    "type": "string",
                    "example": "from swagger"
                },
                "early_remind": {
                    "type": "integer",
                    "example": 30
                },
                "title": {
                    "type": "string",
                    "example": "test ddl"
                }
            }
        },
        "schema.CreateDraftReq": {
            "type": "object",
            "properties": {
                "data_type": {
                    "type": "string",
                    "default": "default",
                    "example": "default"
                },
                "draft": {
                    "$ref": "#/definitions/schema.CreateDraftInput"
                },
                "raw": {
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "schema.CreateDraftResp": {
            "type": "object",
            "properties": {
                "deadline": {
                    "type": "string",
                    "format": "date-time",
                    "example": "2026-03-24T14:30:00+08:00"
                },
                "description": {
                    "type": "string",
                    "example": "from swagger"
                },
                "early_remind": {
                    "type": "integer",
                    "example": 30
                },
                "title": {
                    "type": "string",
                    "example": "test ddl"
                },
                "uuid": {
                    "type": "string",
                    "example": "7a178766-4b8e-4e99-ab4c-843f7dbd95fd"
                }
            }
        },
        "schema.UpdateDraftStatusReq": {
            "type": "object",
            "required": [
                "status"
            ],
            "properties": {
                "status": {
                    "type": "string",
                    "example": "active"
                }
            }
        },
        "schema.UpdateDraftStatusResp": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "integer",
                    "example": 1
                },
                "uuid": {
                    "type": "string",
                    "example": "7a178766-4b8e-4e99-ab4c-843f7dbd95fd"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "DDL Guard API",
	Description:      "This is a DDL Guard server API.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
