basePath: /api/v1
definitions:
  handler.resp:
    properties:
      code:
        type: integer
      data: {}
      message:
        type: string
    type: object
  schema.CreateDraftReq:
    properties:
      data_type:
        type: string
      draft:
        $ref: '#/definitions/schema.CreateDraftResp'
      raw:
        items:
          type: integer
        type: array
    type: object
  schema.CreateDraftResp:
    properties:
      deadline:
        type: string
      description:
        type: string
      early_remind:
        type: integer
      title:
        type: string
      uuid:
        type: string
    type: object
info:
  contact: {}
  description: This is a DDL Guard server API.
  termsOfService: http://swagger.io/terms/
  title: DDL Guard API
  version: "1.0"
paths:
  /ddl/draft:
    post:
      consumes:
      - application/json
      description: 创建DDL草稿
      parameters:
      - description: Create Draft Request
        in: body
        name: req
        required: true
        schema:
          $ref: '#/definitions/schema.CreateDraftReq'
      produces:
      - application/json
      responses:
        "200":
          description: success
          schema:
            allOf:
            - $ref: '#/definitions/handler.resp'
            - properties:
                data:
                  $ref: '#/definitions/schema.CreateDraftResp'
              type: object
      summary: 创建DDL草稿
      tags:
      - DDL
swagger: "2.0"
